DC_Colony = DC_Colony or {}
DC_Colony.Config = DC_Colony.Config or {}

local Config = DC_Colony.Config
Config.EquipmentRequirementDefinitions = Config.EquipmentRequirementDefinitions or {}

local Definitions = {
    ["Colony.Tool.Scavenge"] = {
        label = "Scavenging Tool",
        hintText = "Any scavenging loadout item",
        reasonText = "Baseline loadout item used to unlock scavenging work and scavenger-specific upgrades.",
        searchText = "scavenge scavenging tool loadout",
        supportedFullTypes = {},
        iconFullType = "Base.Crowbar",
        jobTypes = { "Scavenge" },
        autoEquip = true,
        sortOrder = 200,
    },
    ["Scavenge.Access.LockedHome"] = {
        label = "Prying Item",
        hintText = "Crowbar or screwdriver",
        reasonText = "Lets the scavenger force entry into locked homes and other basic closed locations.",
        searchText = "crowbar screwdriver pry prying locked home",
        supportedFullTypes = { "Base.Crowbar", "Base.CrowbarForged", "Base.Screwdriver" },
        iconFullType = "Base.Crowbar",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 210,
    },
    ["Scavenge.Haul.Bag"] = {
        label = "Backpack",
        hintText = "Backpack or duffel bag",
        reasonText = "Adds a carry container so the scavenger can haul more loot before needing to come home.",
        searchText = "backpack duffel bag hauling",
        supportedFullTypes = { "Base.Bag_Schoolbag", "Base.Bag_DuffelBag", "Base.Bag_ToolBag" },
        iconFullType = "Base.Bag_Schoolbag",
        jobTypes = {},
        autoEquip = true,
        sortOrder = 220,
    },
    ["Scavenge.Utility.Light"] = {
        label = "Lightsource",
        hintText = "Flashlight or other light source",
        reasonText = "Reduces dark-area penalties so the scavenger can search interiors more effectively.",
        searchText = "flashlight lightsource light torch lamp",
        supportedFullTypes = { "Base.HandTorch", "Base.FlashLight_AngleHead", "Base.PenLight" },
        iconFullType = "Base.HandTorch",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 230,
    },
    ["Scavenge.Utility.Map"] = {
        label = "Map",
        hintText = "Map or route-planning literature",
        reasonText = "Helps plan routes and supports faster, more efficient scavenging runs.",
        searchText = "map route plan literature",
        supportedFullTypes = { "Base.Map", "Base.MuldraughMap", "Base.WestpointMap" },
        iconFullType = "Base.Map",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 240,
    },
    ["Scavenge.Utility.Pen"] = {
        label = "Pen",
        hintText = "Any pen for route notes",
        reasonText = "Works with maps for route notes, improving the scavenger's planning loadout.",
        searchText = "pen route notes",
        supportedFullTypes = { "Base.Pen", "Base.BluePen", "Base.RedPen" },
        iconFullType = "Base.Pen",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 250,
    },
    ["Scavenge.Access.ElectronicStore"] = {
        label = "Electronics Access Tool",
        hintText = "Screwdriver",
        reasonText = "Needed to open electronics-heavy locations and unlock electronics store scavenging pools.",
        searchText = "electronics access screwdriver store",
        supportedFullTypes = { "Base.Screwdriver", "Base.Screwdriver_Old", "Base.Screwdriver_Improvised" },
        iconFullType = "Base.Screwdriver",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 260,
    },
    ["Scavenge.Extraction.CarpentryHammer"] = {
        label = "Hammer",
        hintText = "Hammer or ball-peen hammer",
        reasonText = "Allows carpentry extraction and stripping when salvaging wooden fixtures and furniture.",
        searchText = "hammer ball peen carpentry",
        supportedFullTypes = { "Base.Hammer", "Base.BallPeenHammer", "Base.ClubHammer" },
        iconFullType = "Base.Hammer",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 270,
    },
    ["Scavenge.Extraction.CarpentrySaw"] = {
        label = "Saw",
        hintText = "Saw or garden saw",
        reasonText = "Pairs with a hammer for carpentry stripping and salvage-focused scavenging.",
        searchText = "saw garden saw carpentry",
        supportedFullTypes = { "Base.Saw", "Base.SmallSaw", "Base.GardenSaw", "Base.CrudeSaw" },
        iconFullType = "Base.Saw",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 280,
    },
    ["Scavenge.Extraction.Plumbing"] = {
        label = "Pipe Wrench",
        hintText = "Pipe wrench",
        reasonText = "Required to extract plumbing-related loot and salvage plumbing fixtures.",
        searchText = "pipe wrench plumbing",
        supportedFullTypes = { "Base.PipeWrench" },
        iconFullType = "Base.PipeWrench",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 290,
    },
    ["Scavenge.Extraction.MetalTorch"] = {
        label = "Metal Torch",
        hintText = "Blow torch",
        reasonText = "Needed for metal salvage jobs and advanced industrial stripping.",
        searchText = "blow torch metal torch welding",
        supportedFullTypes = { "Base.BlowTorch" },
        iconFullType = "Base.BlowTorch",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 300,
    },
    ["Scavenge.Extraction.MetalMask"] = {
        label = "Welding Mask",
        hintText = "Welding mask",
        reasonText = "Needed with a blow torch so the scavenger can safely perform metal salvage work.",
        searchText = "welding mask metal",
        supportedFullTypes = { "Base.WeldingMask" },
        iconFullType = "Base.WeldingMask",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 310,
    },
    ["Scavenge.Access.HeavyEntry"] = {
        label = "Heavy Entry Tool",
        hintText = "Sledgehammer",
        reasonText = "Breaks secure shutters and heavy barriers, unlocking the toughest scavenging entries.",
        searchText = "sledgehammer heavy entry secure shutters vaults",
        supportedFullTypes = { "Base.Sledgehammer", "Base.Sledgehammer2", "Base.SledgehammerForged" },
        iconFullType = "Base.Sledgehammer",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 320,
    },
    ["Scavenge.Haul.Bulk"] = {
        label = "Bulk Sack",
        hintText = "Garbage bag or sandbag",
        reasonText = "Supports carrying bulky loose loot that otherwise gets left behind.",
        searchText = "garbage bag sandbag bulk sack",
        supportedFullTypes = { "Base.Garbagebag", "Base.EmptySandbag" },
        iconFullType = "Base.Garbagebag",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 330,
    },
    ["Scavenge.Haul.Bundle"] = {
        label = "Bundle Rope",
        hintText = "Sheet rope",
        reasonText = "Lets the scavenger bundle heavy items together for transport.",
        searchText = "sheet rope bundle heavy",
        supportedFullTypes = { "Base.SheetRope", "Base.SheetRopeBundle" },
        iconFullType = "Base.SheetRope",
        jobTypes = { "Scavenge" },
        autoEquip = false,
        sortOrder = 340,
    },
}

for key, definition in pairs(Definitions) do
    Config.EquipmentRequirementDefinitions[key] = definition
end

return Config
